#!/bin/bash
######################################################
# Simple brute force tpj.jar build
######################################################
#
JAVAC_OPTS="-nowarn -d classes/ -cp .:..:classes/:lib/qkernel.jar:"$CLASSPATH
#
echo "compiling tpj..."
echo "building common package..." 
javac $JAVAC_OPTS src/common/*.java
if [ $? -eq 0 ]; then
echo "building daemon package..." 
javac $JAVAC_OPTS src/daemon/*.java
fi
if [ $? -eq 0 ]; then   
echo "building util package..." 
javac $JAVAC_OPTS src/util/*.java
fi
if [ $? -eq 0 ]; then   
echo "building model package..." 
javac $JAVAC_OPTS src/model/*.java
fi
#if [ $? -eq 0 ]; then   
#echo "building rpc package..." 
#javac $JAVAC_OPTS src/rpc/*.java
#fi
if [ $? -eq 0 ]; then   
echo "building service package..." 
javac $JAVAC_OPTS src/service/*.java
fi
#
###
if [ $? -eq 0 ]; then   
echo "creating tpj.jar..." 
DIR=$PWD
cd classes/
jar -Mcf ../lib/tpj.jar *
cd $DIR
echo $r
echo "done with no errors"
exit 0
else
echo "***ERRORS in build"
fi
