#!/bin/bash
######################################################
# run the tpj service node as a service
######################################################
#
java -cp lib/mysql.jar:lib/qkernel.jar:lib/tpj.jar daemon/Tpj conf/tpj.conf > log/tpj.log &
